# Standalone AIX PS/2 Makefile for Mesa 1.2.8 libMesaaux.a

CC = cc
CFLAGS = -Hon=ansi -DFBIND=1
INCDIR = ../include
LIBDIR = ../lib
AUX_LIB = libMesaaux.a

SOURCES = glaux.c font.c image.c shapes.c teapot.c vect3d.c xform.c
OBJECTS = $(SOURCES:.c=.o)

all aix-ps2 targets: $(LIBDIR)/$(AUX_LIB)

.c.o:
	$(CC) -c -I$(INCDIR) $(CFLAGS) $<

$(LIBDIR)/$(AUX_LIB): $(OBJECTS)
	-mkdir $(LIBDIR) 2>/dev/null || true
	ar ruv $(AUX_LIB) $(OBJECTS)
	mv $(AUX_LIB) $(LIBDIR)/

clean:
	rm -f *.o $(LIBDIR)/$(AUX_LIB)
